/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MobileIndexRouteImport } from './routes/mobile/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as MobileReplaysRouteImport } from './routes/mobile/replays'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminReplaysRouteImport } from './routes/admin/replays'
import { Route as AdminQuadrasRouteImport } from './routes/admin/quadras'
import { Route as AdminInputBoardsRouteImport } from './routes/admin/input-boards'
import { Route as AdminEdgeDevicesRouteImport } from './routes/admin/edge-devices'
import { Route as AdminCamerasRouteImport } from './routes/admin/cameras'
import { Route as AdminBotoeirasRouteImport } from './routes/admin/botoeiras'
import { Route as AdminArenasRouteImport } from './routes/admin/arenas'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileIndexRoute = MobileIndexRouteImport.update({
  id: '/mobile/',
  path: '/mobile/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MobileReplaysRoute = MobileReplaysRouteImport.update({
  id: '/mobile/replays',
  path: '/mobile/replays',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReplaysRoute = AdminReplaysRouteImport.update({
  id: '/replays',
  path: '/replays',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuadrasRoute = AdminQuadrasRouteImport.update({
  id: '/quadras',
  path: '/quadras',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInputBoardsRoute = AdminInputBoardsRouteImport.update({
  id: '/input-boards',
  path: '/input-boards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEdgeDevicesRoute = AdminEdgeDevicesRouteImport.update({
  id: '/edge-devices',
  path: '/edge-devices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCamerasRoute = AdminCamerasRouteImport.update({
  id: '/cameras',
  path: '/cameras',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBotoeirasRoute = AdminBotoeirasRouteImport.update({
  id: '/botoeiras',
  path: '/botoeiras',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArenasRoute = AdminArenasRouteImport.update({
  id: '/arenas',
  path: '/arenas',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/arenas': typeof AdminArenasRoute
  '/admin/botoeiras': typeof AdminBotoeirasRoute
  '/admin/cameras': typeof AdminCamerasRoute
  '/admin/edge-devices': typeof AdminEdgeDevicesRoute
  '/admin/input-boards': typeof AdminInputBoardsRoute
  '/admin/quadras': typeof AdminQuadrasRoute
  '/admin/replays': typeof AdminReplaysRoute
  '/admin/users': typeof AdminUsersRoute
  '/mobile/replays': typeof MobileReplaysRoute
  '/admin/': typeof AdminIndexRoute
  '/mobile/': typeof MobileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/arenas': typeof AdminArenasRoute
  '/admin/botoeiras': typeof AdminBotoeirasRoute
  '/admin/cameras': typeof AdminCamerasRoute
  '/admin/edge-devices': typeof AdminEdgeDevicesRoute
  '/admin/input-boards': typeof AdminInputBoardsRoute
  '/admin/quadras': typeof AdminQuadrasRoute
  '/admin/replays': typeof AdminReplaysRoute
  '/admin/users': typeof AdminUsersRoute
  '/mobile/replays': typeof MobileReplaysRoute
  '/admin': typeof AdminIndexRoute
  '/mobile': typeof MobileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/arenas': typeof AdminArenasRoute
  '/admin/botoeiras': typeof AdminBotoeirasRoute
  '/admin/cameras': typeof AdminCamerasRoute
  '/admin/edge-devices': typeof AdminEdgeDevicesRoute
  '/admin/input-boards': typeof AdminInputBoardsRoute
  '/admin/quadras': typeof AdminQuadrasRoute
  '/admin/replays': typeof AdminReplaysRoute
  '/admin/users': typeof AdminUsersRoute
  '/mobile/replays': typeof MobileReplaysRoute
  '/admin/': typeof AdminIndexRoute
  '/mobile/': typeof MobileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/arenas'
    | '/admin/botoeiras'
    | '/admin/cameras'
    | '/admin/edge-devices'
    | '/admin/input-boards'
    | '/admin/quadras'
    | '/admin/replays'
    | '/admin/users'
    | '/mobile/replays'
    | '/admin/'
    | '/mobile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/arenas'
    | '/admin/botoeiras'
    | '/admin/cameras'
    | '/admin/edge-devices'
    | '/admin/input-boards'
    | '/admin/quadras'
    | '/admin/replays'
    | '/admin/users'
    | '/mobile/replays'
    | '/admin'
    | '/mobile'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/arenas'
    | '/admin/botoeiras'
    | '/admin/cameras'
    | '/admin/edge-devices'
    | '/admin/input-boards'
    | '/admin/quadras'
    | '/admin/replays'
    | '/admin/users'
    | '/mobile/replays'
    | '/admin/'
    | '/mobile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  MobileReplaysRoute: typeof MobileReplaysRoute
  MobileIndexRoute: typeof MobileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/': {
      id: '/mobile/'
      path: '/mobile'
      fullPath: '/mobile/'
      preLoaderRoute: typeof MobileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/mobile/replays': {
      id: '/mobile/replays'
      path: '/mobile/replays'
      fullPath: '/mobile/replays'
      preLoaderRoute: typeof MobileReplaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/replays': {
      id: '/admin/replays'
      path: '/replays'
      fullPath: '/admin/replays'
      preLoaderRoute: typeof AdminReplaysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quadras': {
      id: '/admin/quadras'
      path: '/quadras'
      fullPath: '/admin/quadras'
      preLoaderRoute: typeof AdminQuadrasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/input-boards': {
      id: '/admin/input-boards'
      path: '/input-boards'
      fullPath: '/admin/input-boards'
      preLoaderRoute: typeof AdminInputBoardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/edge-devices': {
      id: '/admin/edge-devices'
      path: '/edge-devices'
      fullPath: '/admin/edge-devices'
      preLoaderRoute: typeof AdminEdgeDevicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cameras': {
      id: '/admin/cameras'
      path: '/cameras'
      fullPath: '/admin/cameras'
      preLoaderRoute: typeof AdminCamerasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/botoeiras': {
      id: '/admin/botoeiras'
      path: '/botoeiras'
      fullPath: '/admin/botoeiras'
      preLoaderRoute: typeof AdminBotoeirasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/arenas': {
      id: '/admin/arenas'
      path: '/arenas'
      fullPath: '/admin/arenas'
      preLoaderRoute: typeof AdminArenasRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminArenasRoute: typeof AdminArenasRoute
  AdminBotoeirasRoute: typeof AdminBotoeirasRoute
  AdminCamerasRoute: typeof AdminCamerasRoute
  AdminEdgeDevicesRoute: typeof AdminEdgeDevicesRoute
  AdminInputBoardsRoute: typeof AdminInputBoardsRoute
  AdminQuadrasRoute: typeof AdminQuadrasRoute
  AdminReplaysRoute: typeof AdminReplaysRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArenasRoute: AdminArenasRoute,
  AdminBotoeirasRoute: AdminBotoeirasRoute,
  AdminCamerasRoute: AdminCamerasRoute,
  AdminEdgeDevicesRoute: AdminEdgeDevicesRoute,
  AdminInputBoardsRoute: AdminInputBoardsRoute,
  AdminQuadrasRoute: AdminQuadrasRoute,
  AdminReplaysRoute: AdminReplaysRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  MobileReplaysRoute: MobileReplaysRoute,
  MobileIndexRoute: MobileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
