ALTER TABLE public.arenas DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.arena_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.cameras DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.edge_devices DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.input_boards DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.quadras DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.replays DISABLE ROW LEVEL SECURITY;