// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data, error } = await supabase.auth.getSession()
    if (error) {
      console.error('[AUTH ATTACHER ERROR] Failed to get session:', error)
    }
    const token = data.session?.access_token
    if (token) {
      console.log('[AUTH ATTACHER] Attaching bearer token to request')
    }
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
